### ISSUE TITLE
Latest release on MELPA fails to load due to a missing symbol error

### ISSUE THREAD

**Issue by atheriel** [emacsfodder/emacs-theme-creamsody#5]
Current version of the theme on MELPA is out of comission. I'm getting

```
list: Symbol’s value as variable is void: creamsody-dark0
```

when I try to load or compile the theme.

This is likely due in whole to the changes in c9faad5. I would have submitted a fix myself, but I'm not sure if the intended colour here is `creamsody-background0` or `creamsody-black`.

**Comment by jasonm23** [comment]
Fixed in 0.3.5

**Comment by jasonm23** [comment]
I dumbassed it and broke 0.3.5.

0.3.6 should be on Melpa next cycle. (should be dated 2017-01-06)
